Repository MakeContributions/ideahub, pull requests merged in 2022-05, with the labels that each got.

#72 docs(ideas): add open library and language translator
  data/ideas.json
Labels: documentation, enhancement

#73 docs(ideas): add RGB-slider web app
  data/ideas.json
Labels: documentation

#74 docs(projects): add hibi-ciento from TenTraicion
  data/projects.json
Labels: enhancement

#75 docs(ideas): add clock
  data/ideas.json
Labels: documentation
